version: "3.9"

services:
  api:
    build: .
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=controle_gastos;Username=controle_user;Password=controle_gastos123

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: controle_gastos
      POSTGRES_USER: controle_user
      POSTGRES_PASSWORD: controle_gastos123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: